#!/bin/bash
export LC_COLLATE=C
shopt -s extglob

mypath=$1
column_number=$2
value=$3
ret=$(awk -v col_num=$column_number -v val=$value '
    BEGIN{FS=" ";} 
    {
        if ($col_num==val)
            found=1
    }
    END{print found}
' $mypath)
if [ "$ret" = 1 ]
then
    echo "true"
else
    echo "false"
fi